name: DockerHub Push
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build
        run: docker build -t joaovitorsd/gerenciamento-pessoas-frotend .
      - name: Docker Push
        run: docker push joaovitorsd/gerenciamento-pessoas-frotend
